# Generated by Django 5.1.3 on 2025-01-18 19:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('total_inventory_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_liabilities', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_liabilities_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('daily_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('daily_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('net_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
            options={
                'verbose_name_plural': 'Balance',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('wait_for_paid', 'WAIT_FOR_PAID'), ('pending', 'PENDING'), ('paid', 'PAID'), ('wait_for_fulfilment', 'WAIT_FOR_FULFILMENT'), ('fulfilled', 'FULFILLED'), ('cancelled', 'CANCELLED')], default='pending', max_length=255)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('nip', models.CharField(blank=True, max_length=255)),
                ('area_code', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(max_length=255, null=True)),
                ('address_street', models.CharField(max_length=255, null=True)),
                ('address_building_number', models.IntegerField(null=True)),
                ('address_apartment_number', models.IntegerField(blank=True, null=True)),
                ('zip_code', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketProduct',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierObligation',
            fields=[
                ('obligation_id', models.AutoField(primary_key=True, serialize=False)),
                ('obligation_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('obligation_date', models.DateField(auto_now_add=True)),
                ('obligation_deadline', models.DateField(null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=10)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('product_quantity', models.IntegerField()),
                ('product_image', models.CharField(blank=True, max_length=255, null=True)),
                ('product_description', models.TextField(blank=True)),
                ('product_discount', models.IntegerField(default=0)),
                ('product_price_discounted', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('margin', models.IntegerField(default=10)),
                ('tax', models.IntegerField(default=23)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.productcategory')),
                ('product_market', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.marketproduct')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_product_quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.order')),
                ('order_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.warehouseproduct')),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_quantity', models.IntegerField(default=1)),
                ('product_discount', models.IntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.warehouseproduct')),
            ],
        ),
    ]
