# Generated by Django 5.1.3 on 2024-12-09 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='order_product_amount',
            new_name='order_product_quantity',
        ),
        migrations.RenameField(
            model_name='productwarehouse',
            old_name='product_amount',
            new_name='product_quantity',
        ),
    ]
