# Generated by Django 5.1.3 on 2024-12-09 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_order_product_amount_orderproduct_order_product_quantity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductMarket',
            new_name='MarketProduct',
        ),
        migrations.RenameModel(
            old_name='ProductWarehouse',
            new_name='WarehouseProduct',
        ),
    ]
