# Generated by Django 5.1.3 on 2024-12-15 12:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_order_status_order_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('total_inventory_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_liabilities', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('net_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
            options={
                'verbose_name': 'Dzienne saldo',
                'verbose_name_plural': 'Dzienny balans',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('wait_for_paid', 'Wait_for_paid'), ('pending', 'Pending'), ('paid', 'Paid'), ('wait_for_fulfilment', 'wait_for_fulfilment'), ('fulfilled', 'Fulfilled')], default='pending', max_length=255),
        ),
        migrations.CreateModel(
            name='SupplierObligation',
            fields=[
                ('obligation_id', models.AutoField(primary_key=True, serialize=False)),
                ('obligation_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('obligation_date', models.DateField(auto_now_add=True)),
                ('obligation_deadline', models.DateField(null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=10)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.supplier')),
            ],
        ),
    ]
