# Generated by Django 5.1.3 on 2024-12-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_warehousebalance_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehousebalance',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Daily balance'},
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='warehouseproduct',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
