# Generated by Django 5.1.3 on 2024-12-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_warehousebalance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousebalance',
            name='daily_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
