# Generated by Django 5.1.3 on 2024-12-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_warehousebalance_daily_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousebalance',
            name='daily_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='warehousebalance',
            name='total_liabilities_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
