# Generated by Django 5.1.3 on 2025-01-02 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_warehousebalance_daily_income_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='warehousebalance',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Balance'},
        ),
        migrations.AlterField(
            model_name='warehouseproduct',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.productcategory'),
        ),
    ]
