# Generated by Django 5.1.3 on 2025-01-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_productcategory_alter_warehousebalance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproduct',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
