# Generated by Django 5.1.3 on 2025-01-02 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_warehouseproduct_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='name',
            new_name='category_name',
        ),
    ]
