# Generated by Django 5.1.3 on 2025-01-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_productcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproduct',
            name='margin',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='warehouseproduct',
            name='product_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='warehouseproduct',
            name='product_discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warehouseproduct',
            name='product_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
