# Generated by Django 5.1.3 on 2025-01-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproduct',
            name='product_price_discounted',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
