# Generated by Django 5.1.3 on 2025-01-11 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_cart_session_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='session',
        ),
    ]
