# Generated by Django 5.1.3 on 2025-01-11 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_cart_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='session_uuid',
        ),
    ]
