# Generated by Django 5.1.3 on 2025-01-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_remove_cart_session_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('wait_for_paid', 'WAIT_FOR_PAID'), ('pending', 'PENDING'), ('paid', 'PAID'), ('wait_for_fulfilment', 'WAIT_FOR_FULFILMENT'), ('fulfilled', 'FULFILLED'), ('cancelled', 'CANCELLED')], default='pending', max_length=255),
        ),
    ]
